### ISSUE TITLE
QRcode invalido quando gerado um pix no valor redondo abaixo de 100.00

### ISSUE THREAD

**Issue by ademir10** [pedrofurtado/qrcode_pix_ruby#25]
Boa tarde Pedro! tudo bem?
espero que sim!

passando para dar um feedback relacionado as nossas faturas que foram geradas automaticamente nessa madrugada e notamos que, os QRcodes que foram gerados no valor de 99.00 ficaram ilegíveis para o Bradesco e Itaú.
Fiz mais alguns testes como por exemplo adicionando 1 centavo e o QRcode é lido normalmente, inclusive estou utilizando o mesmo código para isso, justamente para ter certeza se o problema estaria em algum outro parametro, mas não, é realmente o valor informado.

teria alguma sugestão?
tentei passar somente o valor sem as casas decimais ( 99 ) e no Bradesco validou porém no Itaú não.

Resumindo:
se passar o valor 99.00 (não valida o QRcode)
se passar o valor 99.01 (QRcode ok)
se passar o valor 99 sem as casas decimais depois do ponto (valida no Bradesco mas não valida no Itaú)

agora qualquer valor acima de R$100.00 é validado, mesmo que tenhamos zeros no final, exemplo 198.00

qualquer tip é bem vinda, hugs!

**Comment by ademir10** [comment]
já descobrimos o erro, desculpa, o problema estava no nosso código, a variável transaction_id estava pegando o parametro errado e por conta disso tinhamos o problema na geração do QRcode.

vou encerrar aqui e qualquer coisa te dou um toque, valeu brigadão Pedro!

**Comment by pedrofurtado** [comment]
Olá @ademir10 , tudo joia? 

Fico feliz que tenha dado certo! 🍻  De toda maneira, a origem do problema teria sido qrcodes com transaction_id iguais ou com valores invalidos por ex?

Pra auxiliar quem consultar essa issue posteriormente 🤝 

Valeu!

**Comment by ademir10** [comment]
> Olá @ademir10 , tudo joia?
> 
> Fico feliz que tenha dado certo! 🍻 De toda maneira, a origem do problema teria sido qrcodes com transaction_id iguais ou com valores invalidos por ex?
> 
> Pra auxiliar quem consultar essa issue posteriormente 🤝
> 
> Valeu!

Exatamente Pedro, estávamos passando um id de outra table onde sempre o valor era igual a 1 em todos os clientes.

Brigadão valeu!
