### ISSUE TITLE
payment status

### ISSUE THREAD

**Issue by kozfelipe** [pedrofurtado/qrcode_pix_ruby#26]
Oi @pedrofurtado ótimo projeto.
Gostaria de saber se existe retorno de status do pagamento ou o script somente gera o QR Code. Se caso positivo, eu preciso de algum cadastro especial junto ao banco? Grato.

**Comment by pedrofurtado** [comment]
Oi @kozfelipe , tudo joia? 👋 

Acredito q essas issues podem ajudar a esclarecer a dúvida pra ti, veja se tem relação:

https://github.com/pedrofurtado/qrcode_pix_ruby/issues/23

 https://github.com/pedrofurtado/qrcode_pix_ruby/issues/24#issuecomment-1188492822 (deste comentario até o fim da conversa ✌️ )
 
 Surgindo algum ponto de dúvida, poste por aqui bele. Esclareço no q for preciso. Tmj!

**Comment by kozfelipe** [comment]
@pedrofurtado, agora está esclarecido.
Estou vendo que preciso de uma instituição intermediária para apontar o weebhook.
Agradeço pela rápida resposta
