### ISSUE TITLE
Bug no CRC16, falta de zero à esquerda

### ISSUE THREAD

**Issue by odairbr** [pedrofurtado/qrcode_pix_ruby#29]
Durante a geração de um payload, foi observado que o valor do campo de _CRC_ foi gerado como `AA8`, em vez de `0AA8`. Após tentar efetuar o pagamento, foi identificado que o valor incorreto de _CRC_ causou uma falha na transação. Ao analisar o problema, verificou-se que faltou o zero à esquerda para completar o valor de _CRC_ com quatro caracteres.

Grato

**Comment by odairbr** [comment]
Eu testei aqui e o `rjust(4, '0')` já poderia resolver.
O que vocês acham?

```ruby
"#{ID_CRC16}04#{result.to_s(16).upcase.rjust(4, '0')}"
```

**Comment by odairbr** [comment]
Abri o PR https://github.com/pedrofurtado/qrcode_pix_ruby/pull/30
Obrigado

**Comment by pedrofurtado** [comment]
@odairbr  v0.5.1 lançada 🎉 -> https://rubygems.org/gems/qrcode_pix_ruby/versions/0.5.1
