### ISSUE TITLE
Dúvida: o que acontece após Pix ser efetuado?

### ISSUE THREAD

**Issue by dgomp** [pedrofurtado/qrcode_pix_ruby#32]
Olá, boa noite.

Após o Pix ser efetuado, o sistema detecta, ou o QR Code continua aparecendo?

**Comment by pedrofurtado** [comment]
A gem apenas gera QR code, sem nenhuma inteligência além dessa geração. 

Se for necessário funcionalidades como expiração de qrcode Pix, detecção de pagamentos (via webhook por ex) e coisas do tipo, é necessário contratar algum fornecedor bancário de api pix, belê? 👍

**Comment by pedrofurtado** [comment]
A gemzinha é análoga aos "geradores de código de barra de boleto", no sentido que possui a funcionalidade de gerar o qrcode com base em metadados, mas nada além disso
